package com.mycompany.maven_lab5_mortalkombat;

import EnemiesFabric.Human;
import EnemiesFabric.Player;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.UnsupportedLookAndFeelException;

/**
 * Класс пользовательского интерфейса
 * @see javax.swing.JFrame
 * @author Мария
 */
public class JFrames extends javax.swing.JFrame {
    
    Game game = new Game();
    Human human = null;
    Player enemy = null;
    Items[] items = new Items[3];
    String nameButton = "";

    
    /**
     * Creates new form JFrame
     */
    public JFrames() {
            initComponents();
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    try {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(JFrames.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (InstantiationException ex) {
                        Logger.getLogger(JFrames.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IllegalAccessException ex) {
                        Logger.getLogger(JFrames.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (UnsupportedLookAndFeelException ex) {
                        Logger.getLogger(JFrames.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            
            //   UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
            try {
                game.ReadFromExcel();
            } catch (IOException ex) {
                Logger.getLogger(JFrames.class.getName()).log(Level.SEVERE, null, ex);
            }
            game.WriteToTable(RecordsTable);
            buttonGroup1.add(SmallPoisonHealRB);
            buttonGroup1.add(BigPoisonHealRB);
            buttonGroup1.add(BackFromDeadItemRB);
            items[0]=new Items("Малое зелье лечение",0);
            items[1]=new Items("Большое зелье лечение",0);
            items[2]=new Items("Крест возрождения",0);
   

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundFrame = new javax.swing.JFrame();
        BackgroundPanel = new javax.swing.JPanel();
        HumanLabelImg = new javax.swing.JLabel();
        Attack = new javax.swing.JButton();
        Protect = new javax.swing.JButton();
        HumanProgressBar = new javax.swing.JProgressBar();
        EnemyLabelImg = new javax.swing.JLabel();
        jProgressBar2 = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        MyHealthLabel = new javax.swing.JLabel();
        HealthEnemyLabel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        Items = new javax.swing.JButton();
        ChangeLocationLabel = new javax.swing.JLabel();
        ContinueDialog = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        RoundStatus = new javax.swing.JLabel();
        ContinueButton = new javax.swing.JButton();
        WinDialog = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        StatusWinner = new javax.swing.JLabel();
        WinnerNameField = new javax.swing.JTextField();
        Label1 = new javax.swing.JLabel();
        Label2 = new javax.swing.JLabel();
        FinishGameButton = new javax.swing.JButton();
        RecordsTableDialog = new javax.swing.JDialog();
        RecordsTablePanel = new javax.swing.JPanel();
        TableName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RecordsTable = new javax.swing.JTable();
        CloseRecordsTableButton = new javax.swing.JButton();
        WhoWinnerDialog = new javax.swing.JDialog();
        WhoWinnerPanel = new javax.swing.JPanel();
        LabelWin = new javax.swing.JLabel();
        Label3 = new javax.swing.JLabel();
        FinishGameButton2 = new javax.swing.JButton();
        ItemsBagDialog = new javax.swing.JDialog();
        ItemsPanel = new javax.swing.JPanel();
        BagItemsLabel = new javax.swing.JLabel();
        SmallPoisonHealRB = new javax.swing.JRadioButton();
        BigPoisonHealRB = new javax.swing.JRadioButton();
        BackFromDeadItemRB = new javax.swing.JRadioButton();
        UseItemsButton = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        SelectedItemErrorDialog = new javax.swing.JDialog();
        UtemErrorPanel = new javax.swing.JPanel();
        Label4 = new javax.swing.JLabel();
        Label5 = new javax.swing.JLabel();
        UnavailableItemButtonOK = new javax.swing.JButton();
        ChooseLocationDialog = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        StartGameButton2 = new javax.swing.JButton();
        NumberLocationsField = new javax.swing.JTextField();
        NumberLocationsLabel = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        InitialPanel = new javax.swing.JPanel();
        NameGameLabel = new javax.swing.JLabel();
        StartGameButton = new javax.swing.JButton();
        OpenRecordsTableButton = new javax.swing.JButton();

        BackgroundPanel.setBackground(new java.awt.Color(255, 255, 255));

        Attack.setBackground(new java.awt.Color(255, 0, 0));
        Attack.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        Attack.setText("Атаковать");
        Attack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttackActionPerformed(evt);
            }
        });

        Protect.setBackground(new java.awt.Color(255, 204, 0));
        Protect.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        Protect.setText("Защититься");
        Protect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProtectActionPerformed(evt);
            }
        });

        HumanProgressBar.setBackground(new java.awt.Color(204, 204, 204));
        HumanProgressBar.setForeground(new java.awt.Color(51, 255, 51));
        HumanProgressBar.setMaximum(80);
        HumanProgressBar.setMinimum(-1);

        jProgressBar2.setBackground(new java.awt.Color(204, 204, 204));
        jProgressBar2.setForeground(new java.awt.Color(0, 255, 0));
        jProgressBar2.setMinimum(-1);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel7.setText("Damage");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel8.setText("Damage");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("16");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("16");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel6.setText("0 level");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 153));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("FIGHT");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        MyHealthLabel.setBackground(new java.awt.Color(255, 255, 255));
        MyHealthLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        MyHealthLabel.setForeground(new java.awt.Color(102, 102, 102));
        MyHealthLabel.setText("80/80");

        HealthEnemyLabel.setBackground(new java.awt.Color(255, 255, 255));
        HealthEnemyLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        HealthEnemyLabel.setForeground(new java.awt.Color(102, 102, 102));
        HealthEnemyLabel.setText("80/80");

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(128, 92, 31));
        jLabel14.setText("experience");

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(128, 92, 31));
        jLabel15.setText("points");

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(113, 90, 16));
        jLabel16.setText("0/40");

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(113, 90, 16));
        jLabel17.setText("00");

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel19.setText("1 level");

        jLabel26.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel27.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 0, 0));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel28.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("You");

        jLabel29.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Items.setBackground(new java.awt.Color(174, 183, 106));
        Items.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        Items.setText("Предметы");
        Items.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemsActionPerformed(evt);
            }
        });

        ChangeLocationLabel.setForeground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout BackgroundPanelLayout = new javax.swing.GroupLayout(BackgroundPanel);
        BackgroundPanel.setLayout(BackgroundPanelLayout);
        BackgroundPanelLayout.setHorizontalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                        .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                .addComponent(ChangeLocationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(161, 161, 161)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HealthEnemyLabel)
                                    .addComponent(jLabel19))
                                .addGap(18, 18, 18)
                                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                        .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(63, 63, 63)
                                        .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(jLabel17)))))
                                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Items, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Attack, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Protect, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundPanelLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(HumanProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(MyHealthLabel)
                                    .addComponent(jLabel6))))
                        .addGap(28, 28, 28))
                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                        .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                    .addComponent(EnemyLabelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                            .addGap(30, 30, 30)
                                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(38, 38, 38))
                                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(30, 30, 30))))
                            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundPanelLayout.createSequentialGroup()
                                .addComponent(HumanLabelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundPanelLayout.createSequentialGroup()
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100))))))
        );
        BackgroundPanelLayout.setVerticalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChangeLocationLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                        .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel10))))
                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                        .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(MyHealthLabel)
                            .addComponent(HumanProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HealthEnemyLabel))
                        .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundPanelLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel19))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                        .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(EnemyLabelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                        .addComponent(HumanLabelImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(Attack, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(Items, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(Protect, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout BackgroundFrameLayout = new javax.swing.GroupLayout(BackgroundFrame.getContentPane());
        BackgroundFrame.getContentPane().setLayout(BackgroundFrameLayout);
        BackgroundFrameLayout.setHorizontalGroup(
            BackgroundFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundFrameLayout.createSequentialGroup()
                .addComponent(BackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BackgroundFrameLayout.setVerticalGroup(
            BackgroundFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(179, 226, 217));

        RoundStatus.setBackground(new java.awt.Color(204, 204, 204));
        RoundStatus.setFont(new java.awt.Font("Comic Sans MS", 1, 42)); // NOI18N
        RoundStatus.setForeground(new java.awt.Color(204, 0, 0));
        RoundStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RoundStatus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ContinueButton.setBackground(new java.awt.Color(114, 218, 142));
        ContinueButton.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        ContinueButton.setText("Дальше");
        ContinueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(ContinueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(RoundStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(RoundStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(ContinueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout ContinueDialogLayout = new javax.swing.GroupLayout(ContinueDialog.getContentPane());
        ContinueDialog.getContentPane().setLayout(ContinueDialogLayout);
        ContinueDialogLayout.setHorizontalGroup(
            ContinueDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContinueDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ContinueDialogLayout.setVerticalGroup(
            ContinueDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContinueDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 255));

        StatusWinner.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        StatusWinner.setForeground(new java.awt.Color(255, 0, 0));
        StatusWinner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StatusWinner.setText("Победа на вашей стороне");

        WinnerNameField.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        WinnerNameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        WinnerNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WinnerNameFieldActionPerformed(evt);
            }
        });

        Label1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Label1.setForeground(new java.awt.Color(102, 102, 102));
        Label1.setText("Введите имя своего персонажа для добавления");

        Label2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Label2.setForeground(new java.awt.Color(102, 102, 102));
        Label2.setText("результата в таблицу рекордов");

        FinishGameButton.setBackground(new java.awt.Color(153, 153, 255));
        FinishGameButton.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        FinishGameButton.setForeground(new java.awt.Color(51, 51, 51));
        FinishGameButton.setText("Закончить игру");
        FinishGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinishGameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(FinishGameButton)
                .addGap(14, 14, 14))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(Label2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(StatusWinner, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WinnerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label1))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(StatusWinner, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(WinnerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FinishGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout WinDialogLayout = new javax.swing.GroupLayout(WinDialog.getContentPane());
        WinDialog.getContentPane().setLayout(WinDialogLayout);
        WinDialogLayout.setHorizontalGroup(
            WinDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WinDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        WinDialogLayout.setVerticalGroup(
            WinDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WinDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        RecordsTablePanel.setBackground(new java.awt.Color(204, 204, 255));

        TableName.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        TableName.setForeground(new java.awt.Color(51, 51, 51));
        TableName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TableName.setText("Таблица рекордов");

        RecordsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Имя", "Количество баллов"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(RecordsTable);

        CloseRecordsTableButton.setBackground(new java.awt.Color(255, 255, 153));
        CloseRecordsTableButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        CloseRecordsTableButton.setForeground(new java.awt.Color(51, 51, 51));
        CloseRecordsTableButton.setText("Закрыть");
        CloseRecordsTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseRecordsTableButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RecordsTablePanelLayout = new javax.swing.GroupLayout(RecordsTablePanel);
        RecordsTablePanel.setLayout(RecordsTablePanelLayout);
        RecordsTablePanelLayout.setHorizontalGroup(
            RecordsTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RecordsTablePanelLayout.createSequentialGroup()
                .addGroup(RecordsTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CloseRecordsTableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RecordsTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(RecordsTablePanelLayout.createSequentialGroup()
                            .addGap(160, 160, 160)
                            .addComponent(TableName, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(RecordsTablePanelLayout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        RecordsTablePanelLayout.setVerticalGroup(
            RecordsTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RecordsTablePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(TableName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CloseRecordsTableButton, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout RecordsTableDialogLayout = new javax.swing.GroupLayout(RecordsTableDialog.getContentPane());
        RecordsTableDialog.getContentPane().setLayout(RecordsTableDialogLayout);
        RecordsTableDialogLayout.setHorizontalGroup(
            RecordsTableDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RecordsTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        RecordsTableDialogLayout.setVerticalGroup(
            RecordsTableDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RecordsTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        WhoWinnerPanel.setBackground(new java.awt.Color(255, 204, 255));

        LabelWin.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        LabelWin.setForeground(new java.awt.Color(255, 0, 0));
        LabelWin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelWin.setText("Победа на вашей стороне");

        Label3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Label3.setForeground(new java.awt.Color(102, 102, 102));
        Label3.setText("К сожалению, Ваш результат не попал в топ 10");

        FinishGameButton2.setBackground(new java.awt.Color(153, 153, 255));
        FinishGameButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        FinishGameButton2.setForeground(new java.awt.Color(51, 51, 51));
        FinishGameButton2.setText("Закончить игру");
        FinishGameButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinishGameButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout WhoWinnerPanelLayout = new javax.swing.GroupLayout(WhoWinnerPanel);
        WhoWinnerPanel.setLayout(WhoWinnerPanelLayout);
        WhoWinnerPanelLayout.setHorizontalGroup(
            WhoWinnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WhoWinnerPanelLayout.createSequentialGroup()
                .addGroup(WhoWinnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WhoWinnerPanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(LabelWin, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(WhoWinnerPanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(WhoWinnerPanelLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(FinishGameButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        WhoWinnerPanelLayout.setVerticalGroup(
            WhoWinnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WhoWinnerPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(LabelWin, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(FinishGameButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout WhoWinnerDialogLayout = new javax.swing.GroupLayout(WhoWinnerDialog.getContentPane());
        WhoWinnerDialog.getContentPane().setLayout(WhoWinnerDialogLayout);
        WhoWinnerDialogLayout.setHorizontalGroup(
            WhoWinnerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(WhoWinnerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        WhoWinnerDialogLayout.setVerticalGroup(
            WhoWinnerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(WhoWinnerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ItemsPanel.setBackground(new java.awt.Color(190, 182, 135));

        BagItemsLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        BagItemsLabel.setForeground(new java.awt.Color(51, 51, 51));
        BagItemsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BagItemsLabel.setText("Мешок предметов");

        SmallPoisonHealRB.setBackground(new java.awt.Color(190, 182, 135));
        SmallPoisonHealRB.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        SmallPoisonHealRB.setText("Малое зелье лечение, 0 шт");
        SmallPoisonHealRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SmallPoisonHealRBActionPerformed(evt);
            }
        });

        BigPoisonHealRB.setBackground(new java.awt.Color(190, 182, 135));
        BigPoisonHealRB.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        BigPoisonHealRB.setText("Большое зелье лечение, 0 шт");
        BigPoisonHealRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BigPoisonHealRBActionPerformed(evt);
            }
        });

        BackFromDeadItemRB.setBackground(new java.awt.Color(190, 182, 135));
        BackFromDeadItemRB.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        BackFromDeadItemRB.setText("Крест возрождения, 0 шт");

        UseItemsButton.setBackground(new java.awt.Color(239, 237, 14));
        UseItemsButton.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        UseItemsButton.setText("Использовать");
        UseItemsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UseItemsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ItemsPanelLayout = new javax.swing.GroupLayout(ItemsPanel);
        ItemsPanel.setLayout(ItemsPanelLayout);
        ItemsPanelLayout.setHorizontalGroup(
            ItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemsPanelLayout.createSequentialGroup()
                .addGroup(ItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ItemsPanelLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(ItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BigPoisonHealRB)
                            .addComponent(BackFromDeadItemRB, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SmallPoisonHealRB, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BagItemsLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ItemsPanelLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(UseItemsButton)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        ItemsPanelLayout.setVerticalGroup(
            ItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemsPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(BagItemsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(SmallPoisonHealRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BigPoisonHealRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BackFromDeadItemRB)
                .addGap(50, 50, 50)
                .addComponent(UseItemsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ItemsBagDialogLayout = new javax.swing.GroupLayout(ItemsBagDialog.getContentPane());
        ItemsBagDialog.getContentPane().setLayout(ItemsBagDialogLayout);
        ItemsBagDialogLayout.setHorizontalGroup(
            ItemsBagDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ItemsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ItemsBagDialogLayout.setVerticalGroup(
            ItemsBagDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ItemsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        UtemErrorPanel.setBackground(new java.awt.Color(243, 120, 120));

        Label4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Label4.setForeground(new java.awt.Color(51, 51, 51));
        Label4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label4.setText("Вы не можете использовать ");

        Label5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Label5.setForeground(new java.awt.Color(51, 51, 51));
        Label5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label5.setText("этот предмет");

        UnavailableItemButtonOK.setBackground(new java.awt.Color(204, 204, 204));
        UnavailableItemButtonOK.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        UnavailableItemButtonOK.setForeground(new java.awt.Color(51, 51, 51));
        UnavailableItemButtonOK.setText("ОК");
        UnavailableItemButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnavailableItemButtonOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UtemErrorPanelLayout = new javax.swing.GroupLayout(UtemErrorPanel);
        UtemErrorPanel.setLayout(UtemErrorPanelLayout);
        UtemErrorPanelLayout.setHorizontalGroup(
            UtemErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UtemErrorPanelLayout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(UtemErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UtemErrorPanelLayout.createSequentialGroup()
                        .addComponent(Label4)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UtemErrorPanelLayout.createSequentialGroup()
                        .addComponent(Label5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135))))
            .addGroup(UtemErrorPanelLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(UnavailableItemButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        UtemErrorPanelLayout.setVerticalGroup(
            UtemErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UtemErrorPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(Label4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(UnavailableItemButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout SelectedItemErrorDialogLayout = new javax.swing.GroupLayout(SelectedItemErrorDialog.getContentPane());
        SelectedItemErrorDialog.getContentPane().setLayout(SelectedItemErrorDialogLayout);
        SelectedItemErrorDialogLayout.setHorizontalGroup(
            SelectedItemErrorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UtemErrorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SelectedItemErrorDialogLayout.setVerticalGroup(
            SelectedItemErrorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UtemErrorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        StartGameButton2.setText("Start to play");
        StartGameButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartGameButton2ActionPerformed(evt);
            }
        });

        NumberLocationsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberLocationsFieldActionPerformed(evt);
            }
        });

        NumberLocationsLabel.setText("Enter number of locations");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(NumberLocationsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(NumberLocationsField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(StartGameButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumberLocationsField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumberLocationsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(StartGameButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout ChooseLocationDialogLayout = new javax.swing.GroupLayout(ChooseLocationDialog.getContentPane());
        ChooseLocationDialog.getContentPane().setLayout(ChooseLocationDialogLayout);
        ChooseLocationDialogLayout.setHorizontalGroup(
            ChooseLocationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ChooseLocationDialogLayout.setVerticalGroup(
            ChooseLocationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChooseLocationDialogLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InitialPanel.setBackground(new java.awt.Color(255, 255, 255));

        NameGameLabel.setFont(new java.awt.Font("Comic Sans MS", 2, 24)); // NOI18N
        NameGameLabel.setForeground(new java.awt.Color(204, 204, 0));
        NameGameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameGameLabel.setText("Mortal Kombat");

        StartGameButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        StartGameButton.setText("Начать новую игру");
        StartGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartGameButtonActionPerformed(evt);
            }
        });

        OpenRecordsTableButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        OpenRecordsTableButton.setText("Посмотреть таблицу \nрезультатов");
        OpenRecordsTableButton.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        OpenRecordsTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenRecordsTableButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InitialPanelLayout = new javax.swing.GroupLayout(InitialPanel);
        InitialPanel.setLayout(InitialPanelLayout);
        InitialPanelLayout.setHorizontalGroup(
            InitialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InitialPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(OpenRecordsTableButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(StartGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(InitialPanelLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(NameGameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InitialPanelLayout.setVerticalGroup(
            InitialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InitialPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(NameGameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(InitialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OpenRecordsTableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StartGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InitialPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InitialPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Кнопка начала игры
     */
    private void StartGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartGameButtonActionPerformed
        ChooseLocationDialog.setVisible(true);
        ChooseLocationDialog.setBounds(200, 100, 500, 300);   
    }//GEN-LAST:event_StartGameButtonActionPerformed

    /**
     * Кнопка продолжения игры после завершения раунда
     */
    private void ContinueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueButtonActionPerformed

        enemy=game.fight.NewRound(human, EnemyLabelImg, HumanProgressBar, jProgressBar2, 
                jLabel5, jLabel10, HealthEnemyLabel, game.action);
        game.change.NewRoundTexts(human, enemy, HumanProgressBar, jProgressBar2, 
                jLabel17, jLabel16, jLabel6, jLabel19, MyHealthLabel, HealthEnemyLabel, jLabel9,
                jLabel26, jLabel27, game.fight.i, items, SmallPoisonHealRB, BigPoisonHealRB, BackFromDeadItemRB);

        ContinueDialog.dispose();
    }//GEN-LAST:event_ContinueButtonActionPerformed

    private void WinnerNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WinnerNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WinnerNameFieldActionPerformed

    /**
     * Кнопка завершения игры
     */
    private void FinishGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinishGameButtonActionPerformed
        try {
            game.EndGameTop(human, WinnerNameField, RecordsTable);
        } catch (IOException ex) {
            Logger.getLogger(JFrames.class.getName()).log(Level.SEVERE, null, ex);
        }
        WinDialog.dispose();
        WinnerNameField.setText("");
    }//GEN-LAST:event_FinishGameButtonActionPerformed

    /**
     * Кнопка закрытия таблицы рейтинга
     */
    private void CloseRecordsTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseRecordsTableButtonActionPerformed
        RecordsTableDialog.dispose();
    }//GEN-LAST:event_CloseRecordsTableButtonActionPerformed

    /**
     * Кнопка открытия таблицы с рейтингом
     */
    private void OpenRecordsTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenRecordsTableButtonActionPerformed
        RecordsTableDialog.setVisible(true);
        RecordsTableDialog.setBounds(100, 100, 580, 450);
    }//GEN-LAST:event_OpenRecordsTableButtonActionPerformed

    /**
     * Кнопка завершения игры при попадании в топ 10 игроков
     */
    private void FinishGameButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinishGameButton2ActionPerformed
        WhoWinnerDialog.dispose();
    }//GEN-LAST:event_FinishGameButton2ActionPerformed

    private void SmallPoisonHealRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SmallPoisonHealRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SmallPoisonHealRBActionPerformed

    private void BigPoisonHealRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BigPoisonHealRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BigPoisonHealRBActionPerformed

     /**
     * Кнопка использования предметов
     */
    private void UseItemsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UseItemsButtonActionPerformed
        if(SmallPoisonHealRB.isSelected()){
            nameButton="jRadioButton1";
        }
        if(BigPoisonHealRB.isSelected()){
            nameButton="jRadioButton2";
        }
        if(BackFromDeadItemRB.isSelected()){
            nameButton="jRadioButton3";
        }
        game.action.UseItem(human, items, nameButton, SelectedItemErrorDialog, ItemsBagDialog);
        game.action.HP(human, HumanProgressBar);
        MyHealthLabel.setText(human.getHealth() + "/" + human.getMaxHealth());
        game.change.BagText(items, SmallPoisonHealRB, BigPoisonHealRB, BackFromDeadItemRB);
    }//GEN-LAST:event_UseItemsButtonActionPerformed

    /**
     * Кнопка невозможности использования предмета
     */
    private void UnavailableItemButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnavailableItemButtonOKActionPerformed
        SelectedItemErrorDialog.dispose();
    }//GEN-LAST:event_UnavailableItemButtonOKActionPerformed
    
     /**
     * Кнопка выбора количества локаций в игре
     */
    int locations = 0;
    ImageFixer imfixer = new ImageFixer();
    private void StartGameButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartGameButton2ActionPerformed
        this.locations = Integer.parseInt(NumberLocationsField.getText());
        ChooseLocationDialog.setVisible(false);
        game.location=this.locations;
          
        BackgroundFrame.setVisible(rootPaneCheckingEnabled);
        BackgroundFrame.setSize(1000,600);
        
        ImageIcon img = new ImageIcon(System.getProperty("user.dir")+"/IMGSource/MainHero.jpg");
        HumanLabelImg.setIcon(imfixer.getScaledImage(img.getImage()));
        human = game.NewHuman(HumanProgressBar, this.locations);
        enemy = game.NewEnemy(EnemyLabelImg, jLabel5, jLabel10, HealthEnemyLabel, jProgressBar2);
        game.change.NewRoundTexts(human, enemy, HumanProgressBar, jProgressBar2, 
                jLabel17, jLabel16, jLabel6, jLabel19, MyHealthLabel, HealthEnemyLabel, jLabel9,
                jLabel26, jLabel27, game.fight.i, items, SmallPoisonHealRB, BigPoisonHealRB, BackFromDeadItemRB);
        
        ChangeLocationLabel.setText("");
        
    }//GEN-LAST:event_StartGameButton2ActionPerformed

    private void NumberLocationsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberLocationsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumberLocationsFieldActionPerformed

    /**
     * Кнопка получения списка доступных предметов
     */
    private void ItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemsActionPerformed
        ItemsBagDialog.setVisible(true);
        ItemsBagDialog.setBounds(300, 200, 430, 350);
    }//GEN-LAST:event_ItemsActionPerformed

    /**
     * Кнопка защиты противника
     */
    private void ProtectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProtectActionPerformed
        game.fight.Hit(human, enemy, 0, HealthEnemyLabel, MyHealthLabel, ContinueDialog,
            RoundStatus, game.action, HumanProgressBar, jProgressBar2, WinDialog,
            WhoWinnerDialog, BackgroundFrame, game.getResults(), StatusWinner, LabelWin,
            jLabel26, jLabel29, jLabel27, items, BackFromDeadItemRB,  ChangeLocationLabel, BackgroundPanel);
    }//GEN-LAST:event_ProtectActionPerformed

    /**
     * Кнопка атаки
     */
    private void AttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttackActionPerformed
        game.fight.Hit(human, enemy, 1, HealthEnemyLabel, MyHealthLabel, ContinueDialog, RoundStatus, game.action, HumanProgressBar, jProgressBar2, WinDialog, WhoWinnerDialog, BackgroundFrame, game.getResults(), StatusWinner, LabelWin,
            jLabel26, jLabel29, jLabel27, items, BackFromDeadItemRB,  ChangeLocationLabel, BackgroundPanel);
    }//GEN-LAST:event_AttackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Attack;
    private javax.swing.JRadioButton BackFromDeadItemRB;
    private javax.swing.JFrame BackgroundFrame;
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JLabel BagItemsLabel;
    private javax.swing.JRadioButton BigPoisonHealRB;
    private javax.swing.JLabel ChangeLocationLabel;
    private javax.swing.JDialog ChooseLocationDialog;
    private javax.swing.JButton CloseRecordsTableButton;
    private javax.swing.JButton ContinueButton;
    private javax.swing.JDialog ContinueDialog;
    private javax.swing.JLabel EnemyLabelImg;
    private javax.swing.JButton FinishGameButton;
    private javax.swing.JButton FinishGameButton2;
    private javax.swing.JLabel HealthEnemyLabel;
    private javax.swing.JLabel HumanLabelImg;
    private javax.swing.JProgressBar HumanProgressBar;
    private javax.swing.JPanel InitialPanel;
    private javax.swing.JButton Items;
    private javax.swing.JDialog ItemsBagDialog;
    private javax.swing.JPanel ItemsPanel;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label3;
    private javax.swing.JLabel Label4;
    private javax.swing.JLabel Label5;
    private javax.swing.JLabel LabelWin;
    private javax.swing.JLabel MyHealthLabel;
    private javax.swing.JLabel NameGameLabel;
    private javax.swing.JTextField NumberLocationsField;
    private javax.swing.JLabel NumberLocationsLabel;
    private javax.swing.JButton OpenRecordsTableButton;
    private javax.swing.JButton Protect;
    private javax.swing.JTable RecordsTable;
    private javax.swing.JDialog RecordsTableDialog;
    private javax.swing.JPanel RecordsTablePanel;
    private javax.swing.JLabel RoundStatus;
    private javax.swing.JDialog SelectedItemErrorDialog;
    private javax.swing.JRadioButton SmallPoisonHealRB;
    private javax.swing.JButton StartGameButton;
    private javax.swing.JButton StartGameButton2;
    private javax.swing.JLabel StatusWinner;
    private javax.swing.JLabel TableName;
    private javax.swing.JButton UnavailableItemButtonOK;
    private javax.swing.JButton UseItemsButton;
    private javax.swing.JPanel UtemErrorPanel;
    private javax.swing.JDialog WhoWinnerDialog;
    private javax.swing.JPanel WhoWinnerPanel;
    private javax.swing.JDialog WinDialog;
    private javax.swing.JTextField WinnerNameField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
